service: users-api-private
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  environment:
    USER_POOL_ID: 
      Fn::ImportValue: UserpoolID

package:
  individually: true

functions:
  userDetail:
    handler: handler.userDetail
    events:
      - http:
          path: /user/detail
          method: post
          authorizer:
            name: auth
            identitySource: method.request.header.Authorization
            type: token
    package:
      patterns:
        - '!node_modules'
        - '!auth.js'
  auth:
    handler: auth.auth
    package:
      patterns:
        - '!handler.js'
